User.all
Truck.destroy_all
Location.destroy_all
Review.destroy_all
Favorite.destroy_all
Schedule.destroy_all
Item.destroy_all
Neighborhood.destroy_all
Category.destroy_all

neighborhood_1 = Neighborhood.create(name: "Midtown")
neighborhood_2 = Neighborhood.create(name: "Jamaica")
neighborhood_3 = Neighborhood.create(name: "Astoria")

loc1 = Location.create(street_address: "300 West 55th Street", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc2 = Location.create(street_address: "3105 Astoria Blvd S", city: "Astoria", state: "NY", zip: "11101", neighborhood_id: neighborhood_3.id)
loc3 = Location.create(street_address: "11811 84th Avenue", city: "Kew Gardens", state: "NY", zip: "11415", neighborhood_id: neighborhood_2.id)
loc4 = Location.create(street_address: "Columbus Circle", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc5 = Location.create(street_address: "Bryant Park", city: "New York", state: "NY", zip: "10018", neighborhood_id: neighborhood_1.id)

loc6 = Location.create(street_address: "102 W 35th St", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc7 = Location.create(street_address: "655 W 34th St", city: "New York", state: "NY", zip: "110001", neighborhood_id: neighborhood_1.id)
loc8 = Location.create(street_address: "390 7th Ave", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc9 = Location.create(street_address: "24 Broadway", city: "New York", state: "NY", zip: "10004", neighborhood_id: neighborhood_1.id)
loc10 = Location.create(street_address: "142 John Street", city: "New York", state: "NY", zip: "10038", neighborhood_id: neighborhood_1.id)
loc11 = Location.create(street_address: "95 Wall Street", city: "New York", state: "NY", zip: "10005", neighborhood_id: neighborhood_1.id)
loc12 = Location.create(street_address: "124 University Pl", city: "New York", state: "NY", zip: "10003", neighborhood_id: neighborhood_1.id)
loc13 = Location.create(street_address: "Bryant Park", city: "New York", state: "NY", zip: "10018", neighborhood_id: neighborhood_1.id)
loc14 = Location.create(street_address: "162 W 56th St", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc15 = Location.create(street_address: "23 3rd Ave", city: "New York", state: "NY", zip: "10003", neighborhood_id: neighborhood_1.id)
loc16 = Location.create(street_address: "1270 Broadway", city: "New York", state: "NY", zip: "10001", neighborhood_id: neighborhood_1.id)
loc17 = Location.create(street_address: "152 W 49th St", city: "New York", state: "NY", zip: "10019", neighborhood_id: neighborhood_1.id)
loc18 = Location.create(street_address: "723 3rd Ave", city: "New York", state: "NY", zip: "10017", neighborhood_id: neighborhood_1.id)
loc19 = Location.create(street_address: "132 Wooster St", city: "New York", state: "NY", zip: "10012", neighborhood_id: neighborhood_1.id)
loc20 = Location.create(street_address: "41 E 51st St", city: "New York", state: "NY", zip: "10022", neighborhood_id: neighborhood_1.id)
# loc25 = Location.create(street_address: "56 Jay Street", city: "Brooklyn", state: "NY", zip: "11201", neighborhood_id: neighborhood_1.id)

priyam = User.create(f_name: "Priyam", l_name: "Sarma", email: "priyam.sarma@gmail.com", username: "psarma89", password: "priyam", password_confirmation: "priyam", location_id: loc1.id)
rochel = User.create(f_name: "Rochel", l_name: "Levi", email: "rochel.levi@gmail.com", username: "rlevi96", password: "rochel", password_confirmation: "rochel", location_id: loc2.id)
mark = User.create(f_name: "Mark", l_name: "White", email: "mark@gmail.com", username: "mwhite", password: "markwhite", password_confirmation: "markwhite", location_id: loc2.id)
jazmin = User.create(f_name: "Jazmin", l_name: "Sanchez", email: "jsanchez@gmail.com", username: "jslovespuppies", password: "jazmin", password_confirmation: "jazmin", location_id: loc2.id)
mike = User.create(f_name: "Mike", l_name: "Samet", email: "msamet@gmail.com", username: "mickey", password: "mikesamet", password_confirmation: "mikesamet", location_id: loc2.id)
frankie = User.create(f_name: "Frankie", l_name: "Chen", email: "fchen@gmail.com", username: "frankc", password: "frankie", password_confirmation: "frankie", location_id: loc2.id)
craig = User.create(f_name: "Craig", l_name: "Chu", email: "craigchu@gmail.com", username: "craigndiane", password: "craigchu", password_confirmation: "craigchu", location_id: loc2.id)
greg = User.create(f_name: "Greg", l_name: "Zelikovsky", email: "gzelikov@gmail.com", username: "zelikov", password: "gregory", password_confirmation: "gregory", location_id: loc2.id)
martin = User.create(f_name: "Martin", l_name: "Weiss", email: "weiss.marty@gmail.com", username: "marty", password: "martin", password_confirmation: "martin", location_id: loc2.id)


cat1 = Category.create(name: "Halal")
cat2 = Category.create(name: "Jamaican")
cat3 = Category.create(name: "Mexican")
cat4 = Category.create(name: "Juice")
cat5 = Category.create(name: "Dessert")
cat6 = Category.create(name: "Sandwiches")
cat7 = Category.create(name: "Vegan")
cat8 = Category.create(name: "Lebanese")
cat9 = Category.create(name: "Pizza")
cat10 = Category.create(name: "Seafood")
cat11 = Category.create(name: "Korean")
cat12 = Category.create(name: "Greek")
cat13 = Category.create(name: "Asian")
cat14 = Category.create(name: "Burgers")
cat15 = Category.create(name: "German")


truck1 = Truck.create(name: "The Halal Guys", category_id: cat1.id, location_id: loc1.id, img_url: "http://newyork.seriouseats.com/images/2012/10/20121002-halal-taste-test-famous-halal-52nd-cart.jpg")
truck2 = Truck.create(name: "Jus by Julie", category_id: cat4.id, location_id: loc4.id, img_url: "https://yeahthatskosher.com/wp-content/uploads/2016/11/JUS-by-Julie-kosher-food-juice-truck-nyc.png")
truck3 = Truck.create(name: "Wafels & Dinges", category_id: cat5.id, location_id: loc6.id, description: "Gorilla Cheese NYC is leading the NYC food truck revolution, taking comfort food and home cooking to a new level. We use only use fresh baked bread delivered from our local bakeries, and a wide variety of delicious cheeses. But what makes our sandwiches extra special is that they're always made with lots of love." , img_url: 'http://cravedujour.com/wp-content/uploads/2014/05/wafelsanddinges.jpg')
truck4 = Truck.create(name: "Gorilla Cheese NYC", category_id: cat6.id, location_id: loc7.id, description: "Gorilla Cheese NYC is leading the NYC food truck revolution, taking comfort food and home cooking to a new level. We use only use fresh baked bread delivered from our local bakeries, and a wide variety of delicious cheeses. But what makes our sandwiches extra special is that they're always made with lots of love.", img_url: 'http://1.bp.blogspot.com/-DA-JFs6ZEUs/UZ7ETjhPDtI/AAAAAAAAZQU/aM1TURU58Wc/s1600/IMG_2371.JPG')
truck5 = Truck.create(name: "The Cinnamon Snail", category_id: cat7.id, location_id: loc8.id, description: "The Vendy Award-winning and ever-so-whimsical Cinnamon Snail trucks have been changing how meat-eaters of NYC & New Jersey see vegan cuisine, with its unbelievably scrumptious selection of sandwiches, burgers, pastries, and more...all organic, all vegan, all insanely tasty. Chef and owner Adam Sobel is a man on a mission to evolve how the world eats; letting go of foods that cause cruelty to animals and damage to our planet, without sacrificing any flavor, one amazing meal from The Cinnamon Snail at a time.", img_url: 'https://roaminghunger.com/img/trucks/original/4de34df0-727c-4f45-a4d5-7ea746204482.jpg' )
truck6 = Truck.create(name: "GoGo Grill", category_id: cat6.id, location_id: loc9.id, description: "GoGo Grill is a cart in Bowling Green serving up tasty sandwiches and salads. Check out the meat and vegetarian english muffin sandwiches, the falafel on naan wrap, or the kale salad! And don't miss out on the daily specials." , img_url: 'https://roaminghunger.com/img/trucks/original/54342595-5f08-4bcc-bce6-394146204482.jpg')
truck7 = Truck.create(name: "Toum NYC", category_id: cat8.id, location_id: loc10.id, description: "Toum is the Lebanese word for garlic, and we serve up authentic Lebanese cuisine with a side of Toum dip on our food truck! Try the falafel, shawarma, kababs, and more!", img_url: 'https://roaminghunger.com/img/trucks/original/57daf112-567c-4f97-8527-059646204482.jpg' )
truck8 = Truck.create(name: "Jiannetto's Pizza", category_id: cat9.id, location_id: loc11.id, description: "Jiannetto’s Pizza & Catering has served as a staple in the NYC street food tradition since back in 1998, when the first iconic truck appeared on Wall Street. ",img_url: 'https://roaminghunger.com/img/trucks/original/4e4d5bb3-03c8-46da-9125-53a446204482.jpg')
truck9 = Truck.create(name: "Luke's Lobster", category_id: cat10.id, location_id: loc12.id, img_url: 'https://roaminghunger.com/img/trucks/original/5578c454-b7c8-40da-bdc7-2a1d46204482.jpg' )
truck10 = Truck.create(name: "Kimchi Taco", category_id: cat11.id, location_id: loc13.id, img_url: 'https://roaminghunger.com/img/trucks/original/4e3dc73b-7080-493a-991f-70b446204482.jpg' )
truck11 = Truck.create(name: "Souvlaki Grill", category_id: cat12.id, location_id: loc14.id, img_url: 'https://roaminghunger.com/img/trucks/original/5924bc5e-10d4-4e7a-9601-422b46204482.jpg')
truck12 = Truck.create(name: "Korilla BBQ", category_id: cat11.id, location_id: loc15.id, img_url: 'https://roaminghunger.com/img/trucks/original/57993acc-f5e4-48cc-8d49-443046204482.png')
truck13 = Truck.create(name: "Coney Shack", category_id: cat13.id, location_id: loc16.id, img_url: 'https://roaminghunger.com/img/trucks/original/562014a7-7a0c-4444-a185-15e046204482.jpg')
truck14 = Truck.create(name: "Frites N Meats", category_id: cat14.id, location_id: loc17.id, img_url: 'https://roaminghunger.com/img/trucks/original/4dd0c735-c3d8-453f-870c-69cc46204482.jpeg')
truck15 = Truck.create(name: "Schnitzel and Things", category_id: cat15.id, location_id: loc18.id, img_url: 'https://roaminghunger.com/img/trucks/original/57d99656-3eb4-4e10-85cf-7eda46204482.jpg')
truck16 = Truck.create(name: "Calexico Cart", category_id: cat3.id, location_id: loc19.id, img_url: 'http://farm5.static.flickr.com/4126/4833118017_2e3be5c471.jpg')
truck17 = Truck.create(name: "El Toro Rojo Truck", category_id: cat3.id, location_id: loc20.id, img_url: 'https://roaminghunger.com/img/trucks/original/596d3f39-5450-4f62-aace-112146204482.jpg')


# review1(title: , content:, rating: , truck_id: , user_id:)
# review2(title: , content:, rating: , truck_id: , user_id:)
# review3(title: , content:, rating: , truck_id: , user_id:)
# review4(title: , content:, rating: , truck_id: , user_id:)
# review5(title: , content:, rating: , truck_id: , user_id:)
# review6(title: , content:, rating: , truck_id: , user_id:)
# review7(title: , content:, rating: , truck_id: , user_id:)
# review8(title: , content:, rating: , truck_id: , user_id:)
# review9(title: , content:, rating: , truck_id: , user_id:)
# review10(title: , content:, rating: , truck_id: , user_id:)
# review11(title: , content:, rating: , truck_id: , user_id:)
# review12(title: , content:, rating: , truck_id: , user_id:)
# review13(title: , content:, rating: , truck_id: , user_id:)
# review14(title: , content:, rating: , truck_id: , user_id:)
# review15(title: , content:, rating: , truck_id: , user_id:)
# review16(title: , content:, rating: , truck_id: , user_id:)
# review17(title: , content:, rating: , truck_id: , user_id:)
# review18(title: , content:, rating: , truck_id: , user_id:)
# review19(title: , content:, rating: , truck_id: , user_id:)
# review20(title: , content:, rating: , truck_id: , user_id:)
# review21(title: , content:, rating: , truck_id: , user_id:)
# review22(title: , content:, rating: , truck_id: , user_id:)
# review23(title: , content:, rating: , truck_id: , user_id:)
# review24(title: , content:, rating: , truck_id: , user_id:)
# review25(title: , content:, rating: , truck_id: , user_id:)

item1 = Item.create(name:"Beef Over Rice", price: 11, truck_id: truck1.id )
item2 = Item.create(name:"Chicken and Beef Combo over Rice", price: 12, truck_id: truck1.id )
item3 = Item.create(name:"Chicken over Rice", price: 9, truck_id: truck1.id )
item4 = Item.create(name:"Chicken and Beef Combo Sandwich", price: 10, truck_id: truck1.id )
item5 = Item.create(name:"Chicken Sandwich", price: 9, truck_id: truck1.id )
item6 = Item.create(name:"Gyro Sandwich", price: 10, truck_id: truck1.id )
item7 = Item.create(name:"Falafel Sandwich", price: 6, truck_id: truck1.id )
item8 = Item.create(name:"Falafel over Rice", price:6, truck_id: truck1.id )

item9 = Item.create(name:"Feta Salad", price:13, truck_id: truck2.id )
item10 = Item.create(name:"Kale Salad with Tempeh", price:13, truck_id: truck2.id )
item10 = Item.create(name:"Quinoa Salad", price:12, truck_id: truck2.id )
item11 = Item.create(name:"Tuna Salad", price: 13, truck_id: truck2.id )
item12 = Item.create(name:"Sweet Spin", price:8, truck_id: truck2.id )
item13 = Item.create(name:"Xtreme Greens", price:8, truck_id: truck2.id )
item14 = Item.create(name:"Chia Berry", price:8, truck_id: truck2.id )
item15 = Item.create(name:"PB Power", price:10, truck_id: truck2.id )
item15 = Item.create(name:"Coconut Water", price:6, truck_id: truck2.id )

# Wafels and Dinges
item16 = Item.create(name:"The Brussels Wafel", price:12, truck_id: truck3.id )
item17 = Item.create(name:"lÃ¨ge wafel", price:12, truck_id: truck3.id )
item18 = Item.create(name:"Mini Wafelini", price:12, truck_id: truck3.id )
item19 = Item.create(name:"de Throwdown wafel", price: 12, truck_id: truck3.id )
item20 = Item.create(name:"Ice Cream Wafel Cone", price:14, truck_id: truck3.id )
item21 = Item.create(name:"BBQ Pulled Pork Wafel", price:13, truck_id: truck3.id )
item22 = Item.create(name:"de bacon + syrup wafel", price:15, truck_id: truck3.id)
item23 = Item.create(name:"chilli con corne", price:10, truck_id: truck3.id )
item24 = Item.create(name:"LiÃ¨ge Wafel", price:11, truck_id: truck3.id )
item25 = Item.create(name:"hot belgian cocoa", price:5, truck_id: truck3.id )
item26 = Item.create(name:"Cold Brew Coffee", price:4, truck_id: truck3.id )
item27 = Item.create(name:"Tea", price:3, truck_id: truck3.id )
item28 = Item.create(name:"Coffee", price:3, truck_id: truck3.id )

# Gorilla Cheese
item29 = Item.create(name:"Build Your Own Sandwich", price:11, truck_id: truck4.id )
item30 = Item.create(name:"#4", price:10, truck_id: truck4.id )
item31 = Item.create(name:"#5", price:10, truck_id: truck4.id )
item32 = Item.create(name:"#6", price: 10, truck_id: truck4.id )
item33 = Item.create(name:"#7", price: 10, truck_id: truck4.id )
item34 = Item.create(name:"#8", price: 10, truck_id: truck4.id )
item35 = Item.create(name:"#9", price: 10, truck_id: truck4.id )
item36 = Item.create(name:"#10", price:10, truck_id: truck4.id )
item37 = Item.create(name:"#11", price:10, truck_id: truck4.id )
item38 = Item.create(name:"#12", price:10, truck_id: truck4.id )
item39 = Item.create(name:"#14", price:10, truck_id: truck2.id )
item40 = Item.create(name:"Tots with Cheese & Bacon", price:9, truck_id: truck4.id )
item41 = Item.create(name:"Mac & Cheese Bites", price:8, truck_id: truck4.id )
item42 = Item.create(name:"Tomato Soup", price:7, truck_id: truck4.id )
item43 = Item.create(name:"Tomato Soup Shooter", price:8, truck_id: truck4.id )
item44 = Item.create(name:"Tater Tots", price:8, truck_id: truck4.id )

# Cinnamon Snail -- vegan
item45 = Item.create(name:"Thai BBQ Tempeh", price:12, truck_id: truck5.id )
item46 = Item.create(name:"Thanksgiving Sandoo", price:12.5, truck_id: truck5.id )
item47 = Item.create(name:"Maple Mustard Tempeh Sandwich", price:10.75, truck_id: truck5.id )
item48 = Item.create(name:"Korean Barbeque Seitan", price: 11.25, truck_id: truck5.id )
item49 = Item.create(name:"Beastmode Burger Deluxe", price: 12, truck_id: truck5.id )
item50 = Item.create(name:"Tamarind Plum Glazed Lentil Burger", price: 12, truck_id: truck5.id )
item51 = Item.create(name:"Smoked Sage Seitan Burger", price: 12, truck_id: truck5.id )
item52 = Item.create(name:"House Salad", price:12, truck_id: truck5.id )
item53 = Item.create(name:"Rosemary Sunflower Crusted Tofu", price:16.5, truck_id: truck5.id )
item54 = Item.create(name:"French Mustard Grilled Seitan", price:15.5, truck_id: truck5.id )
item55 = Item.create(name:"Creamy Mashed Potatoes", price:5.75, truck_id: truck5.id )
item56 = Item.create(name:"Baked Ziti", price:6, truck_id: truck5.id )
item57 = Item.create(name:"Kimchi Tater Tots ", price:6, truck_id: truck5.id )
item58 = Item.create(name:"Baked Cashew Cheese Tater Tots", price:6.5, truck_id: truck5.id )
item59 = Item.create(name:"Jalapeno Mac N Cheese", price:5.5, truck_id: truck5.id )
item60 = Item.create(name:"Red Quinoa Pilaf ", price:6, truck_id: truck5.id )

# Luke's Lobster
item61 = Item.create(name:"lobster Roll", price:18, truck_id: truck6.id )
item62 = Item.create(name:"Crab Roll", price:13, truck_id: truck6.id )
item63 = Item.create(name:"Shrimp Roll", price:9, truck_id: truck6.id )
item64 = Item.create(name:"Luke's Trio", price: 20, truck_id: truck6.id )
item65 = Item.create(name:"Lobster Mac & Cheese", price: 15, truck_id: truck6.id )
item66 = Item.create(name:"Bread Bowl", price: 12, truck_id: truck6.id )
item67 = Item.create(name:"Wild Blue Salad", price:15, truck_id: truck6.id )
item68 = Item.create(name:"Lobster & Gruyere Grilled Cheese.", price:13, truck_id: truck6.id )
item69 = Item.create(name:"Crab & Gruyere Grilled Cheese.", price:10, truck_id: truck6.id )
item70 = Item.create(name:"Clam Chowder", price: 6, truck_id: truck6.id )
item71 = Item.create(name:"Lobster Bisque", price:7, truck_id: truck6.id )
item72 = Item.create(name:"Cape Cod Chips", price:2, truck_id: truck6.id )
item73 = Item.create(name:"Poppy Seed Slaw", price:2, truck_id: truck6.id )
#
# # Kimchi Taco
# item74 = Item.create(name:"Kimchi Taco", price:4, truck_id: truck2.id )
# item75 = Item.create(name:"Big Belly Burrito", price:9.75, truck_id: truck2.id )
# item76 = Item.create(name:"Fresh Kimchi Bowl", price: 9.75, truck_id: truck2.id )
# item77 = Item.create(name:"Spicy Korean Rice Gnocchi", price: 4.75, truck_id: truck2.id )
# item78 = Item.create(name:"Kimchi Arancini", price:5.75, truck_id: truck2.id )
# item79 = Item.create(name:"BBQ Nachos", price:6.75, truck_id: truck2.id )
# item80 = Item.create(name:"Kimchi Fries", price: 6, truck_id: truck2.id )
#
#
# # Souvlaki GR
# item81 = Item.create(name:"Hummus ", price:6, truck_id: truck2.id )
# item82 = Item.create(name:"Eggplant", price:6, truck_id: truck2.id )
# item83 = Item.create(name:"Spicy Feta", price: 6, truck_id: truck2.id )
# item84 = Item.create(name:"Tzatziki", price: 6, truck_id: truck2.id )
# item85 = Item.create(name:"Pork Skewer", price: 3.5, truck_id: truck2.id )
# item86 = Item.create(name:"Chicken Skewer", price:3.5, truck_id: truck2.id )
# item87 = Item.create(name:"Pork Pita", price: 6, truck_id: truck2.id )
# item88 = Item.create(name:"Bifteki (Greek Burger) Pita", price: 7, truck_id: truck2.id )
# item89 = Item.create(name:"Shrimp Pita", price: 7, truck_id: truck2.id )
# item90 = Item.create(name:"Traditional Greek Salad", price: 9, truck_id: truck2.id )
# item91 = Item.create(name:"Hand Cut Fries", price: 5, truck_id: truck2.id )
# item92 = Item.create(name:"Hand Cut Greek Fries", price: 6, truck_id: truck2.id )
#
# # Toum NYC
# item93 = Item.create(name:"Tabouleh Salad", price:5, truck_id: truck2.id )
# item94 = Item.create(name:"Babaghanouj", price:6, truck_id: truck2.id )
# item95 = Item.create(name:"Chicken Shawarma Sandwich", price: 8, truck_id: truck2.id )
# item96 = Item.create(name:"Chicken Shawarma Platter", price: 11, truck_id: truck2.id )
# item97 = Item.create(name:"Beef Kabab Sandwich", price: 8.5, truck_id: truck2.id )
# item98 = Item.create(name:"Beef Kabab Platter", price:11.5, truck_id: truck2.id )
# item99 = Item.create(name:"Makanek Sandwich", price: 8, truck_id: truck2.id )
# item100 = Item.create(name:"Makanek Platter", price: 11, truck_id: truck2.id )
# item101 = Item.create(name:"Grilled Kafta Sandwich", price: 8.5, truck_id: truck2.id )
# item102 = Item.create(name:"Fried Kibbeh", price: 2.5, truck_id: truck2.id )
# item103 = Item.create(name:"Lahem B'ajeen", price: 4, truck_id: truck2.id )
# item104 = Item.create(name:"Spinach Pie", price: 2, truck_id: truck2.id )
# item105 = Item.create(name:"Grape Leaves", price: 6, truck_id: truck2.id )
# item106 = Item.create(name:"Grilled Halloumi Sandwich", price: 8, truck_id: truck2.id )
# item107 = Item.create(name:"Falafel Sandwich", price: 6, truck_id: truck2.id )
# item108 = Item.create(name:"Falafel Platter", price: 9, truck_id: truck2.id )
# item109 = Item.create(name:"Vegetarian Platter", price: 9, truck_id: truck2.id )
#
# # Korilla BBQ
# item110 = Item.create(name:"Spicy Pork Noodle Bowl", price:9.5, truck_id: truck2.id )
# item111 = Item.create(name:"Bulgogi Rice Bowl", price:10, truck_id: truck2.id )
# item112 = Item.create(name:"Hot Chix Rice Bowl", price: 9.5, truck_id: truck2.id )
# item113 = Item.create(name:"Spicy Pork Rice Bowl", price: 9.5, truck_id: truck2.id )
# item114 = Item.create(name:"Tofu Rice Bowl", price: 9.5, truck_id: truck2.id )
# item115 = Item.create(name:"Bulgogi Salad", price:9.5, truck_id: truck2.id )
# item116 = Item.create(name:"Makanek Sandwich", price: 10, truck_id: truck2.id )
# item117 = Item.create(name:"Spicy Pork Salad", price: 9.5, truck_id: truck2.id )
# item118 = Item.create(name:"Hot Chix Salad", price: 9.5, truck_id: truck2.id )
# item119 = Item.create(name:"Tiger Balls", price: 4, truck_id: truck2.id )
#
# # Coney Foodtruck
# item120 = Item.create(name:"Casadia Chicken Beef Or Pork", price:5, truck_id: truck2.id )
# item121 = Item.create(name:"Grill Cheese Chicken, Beef Or Pork", price: 4, truck_id: truck2.id )
# item122 = Item.create(name:"Tripple Grill Cheese", price: 4, truck_id: truck2.id )
# item123 = Item.create(name:"Hot Dogs", price: 2.5, truck_id: truck2.id )
# item124 = Item.create(name:"Tacos", price: 7, truck_id: truck2.id )
